[package]
name = "carbonbot"
version = "1.4.9"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-crawler = "1.8.2"
crypto-msg-parser = "1.4.3"
crypto-ws-client = "2.6.0"
dashmap = "4"
redis = "0.20"
reopen = { version = "1.0.2", features = ["signals"] }
serde_json = "1.0"
signal-hook = { version = "0.3.9", features = ["extended-siginfo"] }
log = "0.4"
env_logger = "0.8"
