[package]
name = "carbonbot"
version = "1.8.0"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-crawler = "3.0.5"
crypto-msg-parser = "1.5.5"
crypto-ws-client = "3.0.6"
redis = "0.20"
reopen = { version = "1.0.2", features = ["signals"] }
serde_json = "1.0"
signal-hook = { version = "0.3.9", features = ["extended-siginfo"] }
log = "0.4"
env_logger = "0.8"

[profile.release]
lto = true
codegen-units = 1
