[package]
name = "crypto-ws-client"
version = "4.0.5"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description = "A versatile websocket client that supports many cryptocurrency exchanges."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-ws-client"
keywords = ["cryptocurrency", "blockchain", "trading", "websocket"]

[dependencies]
async-trait = "0.1.52"
flate2 = "1"
futures-util = "0.3.21"
governor = "0.4.2"
nonzero_ext = "0.3.0"
log = "0.4"
reqwest = { version = "0.11", features = ["gzip"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread",  "time", "sync", "macros"] }
tokio-tungstenite = { version = "0.17.1", features = ["rustls-tls-native-roots"] }

[dev-dependencies]
tokio = { version = "1", features = ["test-util"] }
