[package]
name = "crypto-markets"
version = "1.1.7"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description   = "Fetch trading markets from a cryptocurrency exchange"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-markets"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
chrono = "0.4"
crypto-market-type = "1.0.8"
crypto-pair = "2.2.0"
reqwest = { version = "0.11", features = ["blocking", "gzip", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev_dependencies]
crypto-contract-value = "1.3.4"
test-case = "1"
