[package]
name = "crypto-crawler"
version = "3.2.2"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description   = "A rock-solid cryprocurrency crawler."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-crawler"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
crypto-markets = "1.0.4"
crypto-market-type = "1.0.5"
crypto-pair = "2.0.8"
crypto-rest-client = "0.7.8"
crypto-ws-client = "3.1.2"
fslock = "0.1.8"
lazy_static = "1"
log = "0.4"
rand = "0.8.4"
reqwest = { version = "0.11", features = ["blocking", "gzip"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = "0.23"
strum_macros = "0.23"

[dev_dependencies]
test-case = "1"
env_logger = "0.8"
crypto-msg-parser = "1.7.2"
