[package]
name = "crypto-crawler"
version = "4.0.8"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2021"
description   = "A rock-solid cryprocurrency crawler."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-crawler"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
crypto-markets = "1.1.8"
crypto-market-type = "1.0.8"
crypto-msg-parser = "1.9.8"
crypto-msg-type = "1.0.5"
crypto-pair = "2.2.1"
crypto-rest-client = "0.8.5"
crypto-ws-client = "4.0.7"
fslock = "0.2.1"
once_cell = "1.10.0"
log = "0.4.16"
rand = "0.8.5"
reqwest = { version = "0.11.10", features = ["blocking", "gzip"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "sync", "time"] }

[dev_dependencies]
env_logger = "0.9"
test-case = "1"
tokio = { version = "1", features = ["test-util"] }
