[package]
name = "crypto-rest-client"
version = "0.6.6"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "An restful client for all cryptocurrency exchanges."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-rest-client"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
crypto-market-type = "0.1.6"
lazy_static = "1"
regex = "1"
reqwest = { version = "0.11", features = ["blocking", "gzip", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
strum = "0.20"
strum_macros = "0.20"

[dev_dependencies]
test-case = "1"
